"""
EDM-Takens Skill Router — Decision Triage Channel
===================================================
Deterministic decision flow that routes any time-series analysis
request through the correct methodology path.

Design principle (Garden of Forking Paths countermeasure):
  All decisions are automated, not hand-tuned. The router closes the
  "try parameters until something looks significant" loophole by
  encoding every decision as a fixed rule before any computation runs.

Usage:
  from router import Router
  router = Router(data, n_variables=4, is_binary=True)
  plan = router.route()
  plan.print_plan()
  plan.execute()  # runs the full path

The router answers five questions in strict order:
  Q1: Is this data suitable for EDM/HAVOK at all?
  Q2: Which specific methods should run?
  Q3: What parameters? (auto-detected, not hand-tuned)
  Q4: What validations are MANDATORY vs optional?
  Q5: What is the output labeling? (exploratory/confirmatory)
"""

import os, sys, json, time, inspect
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Tuple
from enum import Enum


# ── Type definitions ──────────────────────────────────────

class DataGrade(Enum):
    """Data quality tier — determines which method family is viable."""
    EXCELLENT = "excellent"   # N>=100, regular, clean → full pipeline
    ADEQUATE = "adequate"     # N>=50, regular, moderate noise → with surrogates
    MARGINAL = "marginal"     # N<50 or irregular → limited methods, strong warnings
    INADEQUATE = "inadequate" # N<20 or very noisy → do NOT use EDM/HAVOK


class AnalysisGoal(Enum):
    """What the user wants to achieve."""
    PREDICT = "predict"                # out-of-sample forecasting
    DETECT_NONLINEARITY = "detect_nl"  # is the system nonlinear?
    CAUSAL_INFERENCE = "causal"        # what drives what?
    PHASE_TRANSITION = "phase"         # when do regime shifts occur?
    EXPLORE = "explore"               # generate hypotheses


class AnalysisLabel(Enum):
    """Output labeling requirement (research-rigor.md principle 7)."""
    EXPLORATORY = "exploratory"    # hypothesis-generating, NOT confirmatory
    CONFIRMATORY = "confirmatory"  # pre-registered, p-value valid


@dataclass
class RouteStep:
    """One step in the execution plan."""
    order: int
    name: str
    module: str           # Python module to call
    function: str         # function name
    mandatory: bool       # can this be skipped?
    args: Dict = field(default_factory=dict)
    rationale: str = ""


@dataclass
class AnalysisPlan:
    """Complete analysis plan generated by the Router."""
    data_grade: DataGrade
    goal: AnalysisGoal
    label: AnalysisLabel
    steps: List[RouteStep] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    blocks: List[str] = field(default_factory=list)

    def print_plan(self):
        """Human-readable plan output."""
        print("\n" + "=" * 64)
        print(f"  ANALYSIS PLAN")
        print(f"  Data Grade: {self.data_grade.value.upper()}")
        print(f"  Goal:       {self.goal.value}")
        print(f"  Label:      {self.label.value.upper()}")
        print("=" * 64)

        if self.blocks:
            print(f"\n  !! BLOCKED ({len(self.blocks)} issues):")
            for b in self.blocks:
                print(f"     [XX] {b}")
            print(f"  => DO NOT PROCEED. Fix blockers before retrying.")

        if self.warnings:
            print(f"\n  !! WARNINGS ({len(self.warnings)}):")
            for w in self.warnings:
                print(f"     [!] {w}")

        if self.steps:
            print(f"\n  EXECUTION PLAN ({len(self.steps)} steps):")
            for s in self.steps:
                tag = "[REQUIRED]" if s.mandatory else "[optional]"
                print(f"  {s.order:2d}. {tag} {s.name}")
                print(f"      → {s.module}.{s.function}()")
                if s.rationale:
                    print(f"      {s.rationale[:70]}")

    def to_dict(self) -> Dict:
        """Serialize plan to dict (for JSON config artifact)."""
        return {
            'data_grade': self.data_grade.value,
            'goal': self.goal.value,
            'label': self.label.value,
            'steps': [{'order': s.order, 'name': s.name,
                       'module': s.module, 'function': s.function,
                       'mandatory': s.mandatory, 'rationale': s.rationale}
                      for s in self.steps],
            'warnings': self.warnings,
            'blocks': self.blocks,
            'timestamp': time.strftime('%Y-%m-%dT%H:%M:%S'),
        }


# ── Router ────────────────────────────────────────────────

class Router:
    """
    Deterministic routing engine for EDM/HAVOK analysis.

    Takes data characteristics → outputs executable plan.
    Every decision is rule-based (no parameter-hopping).
    """

    def __init__(self,
                 n_samples: int,
                 n_variables: int = 1,
                 is_regular: bool = True,
                 is_binary_target: bool = False,
                 snr_estimate: Optional[str] = None,
                 goal: str = "explore",
                 has_preregistration: bool = False,
                 ccm_pairs: Optional[int] = None):
        """
        Parameters
        ----------
        n_samples : int
            Number of time points.
        n_variables : int
            Number of measured variables (columns).
        is_regular : bool
            Is sampling interval uniform?
        is_binary_target : bool
            Is the target variable 0/1 (binary)?
        snr_estimate : str, optional
            "high", "moderate", "low", or None (unknown).
        goal : str
            "predict", "detect_nl", "causal", "phase", "explore"
        has_preregistration : bool
            Has a pre-registration document been written?
        ccm_pairs : int, optional
            Number of pairwise CCM tests planned (Secret 13 routing —
            reference doc: `if ccm_pairs >= 5: active.append(S13)`).
            Defaults to `max(0, n_variables - 1)` (testing every other
            variable against one target) when not given explicitly —
            an approximation, since the router doesn't otherwise know
            how many pairs a causal-inference analysis will actually run.
        """
        self.n = n_samples
        self.n_vars = n_variables
        self.is_regular = is_regular
        self.is_binary = is_binary_target
        self.snr = snr_estimate or "unknown"
        self.has_prereg = has_preregistration
        self.ccm_pairs = (ccm_pairs if ccm_pairs is not None
                          else max(0, n_variables - 1))

        goal_map = {
            "predict": AnalysisGoal.PREDICT,
            "detect_nl": AnalysisGoal.DETECT_NONLINEARITY,
            "causal": AnalysisGoal.CAUSAL_INFERENCE,
            "phase": AnalysisGoal.PHASE_TRANSITION,
            "explore": AnalysisGoal.EXPLORE,
        }
        self.goal = goal_map.get(goal, AnalysisGoal.EXPLORE)

    # ── Q1: Data grading ──────────────────────────────────

    def _grade_data(self) -> DataGrade:
        """Determine data quality tier."""
        if self.n < 20:
            return DataGrade.INADEQUATE
        if not self.is_regular:
            return DataGrade.MARGINAL
        if self.snr == "low":
            return DataGrade.MARGINAL

        if self.n >= 100 and self.snr in ("high", "moderate", "unknown"):
            return DataGrade.EXCELLENT
        elif self.n >= 50:
            return DataGrade.ADEQUATE
        else:
            return DataGrade.MARGINAL

    # ── Q2-Q5: Build plan ─────────────────────────────────

    def route(self) -> AnalysisPlan:
        """Execute the full routing logic. Returns AnalysisPlan."""
        grade = self._grade_data()
        label = (AnalysisLabel.CONFIRMATORY if self.has_prereg
                 else AnalysisLabel.EXPLORATORY)

        plan = AnalysisPlan(data_grade=grade, goal=self.goal, label=label)

        # ── Blockers ──
        if grade == DataGrade.INADEQUATE:
            plan.blocks.append(
                f"N={self.n} is below minimum (20). "
                f"EDM/HAVOK cannot reliably reconstruct an attractor. "
                f"Switch to Bayesian state-space models or Gaussian processes.")
            return plan

        if self.goal == AnalysisGoal.PREDICT and grade == DataGrade.MARGINAL:
            plan.blocks.append(
                f"Prediction requested but N={self.n} with "
                f"irregular/noisy data cannot support out-of-sample forecasting. "
                f"Downgrade goal to 'explore' or collect more data.")

        if self.goal == AnalysisGoal.PHASE_TRANSITION and self.n < 100:
            plan.warnings.append(
                f"Phase transition detection needs N>=100 for reliable "
                f"kurtosis estimation. Results will be SUGGESTIVE only.")

        # ── Warnings ──
        if self.is_binary:
            plan.warnings.append(
                "Binary target: EDM rho ceiling ~0.87. "
                "Prefer continuous covariates for attractor reconstruction.")

        if self.n_vars >= 3 and self.n < 100:
            plan.warnings.append(
                f"Multiview embedding recommended (N={self.n}<100, "
                f"K={self.n_vars} variables). Saves data-efficiency loss.")

        if label == AnalysisLabel.EXPLORATORY:
            plan.warnings.append(
                "No pre-registration detected. Results will be labeled "
                "EXPLORATORY. Do not use confirmatory language.")

        # ── Build step sequence ──
        step_order = 0

        # Step 1: Environment (always)
        step_order += 1
        plan.steps.append(RouteStep(
            order=step_order, name="Environment Validation",
            module="environment_check", function="validate_environment",
            mandatory=True,
            rationale="Verify all dependencies before any computation."))

        # Step 2: Auditor (always)
        step_order += 1
        plan.steps.append(RouteStep(
            order=step_order, name="Configuration Audit",
            module="edm_auditor", function="audit_pipeline",
            mandatory=True,
            args={"n": self.n, "is_binary": self.is_binary},
            rationale="Firewall: block invalid configs before computation."))

        # Step 3: Tau optimization (if applicable)
        if self.n >= 30:
            step_order += 1
            plan.steps.append(RouteStep(
                order=step_order, name="Tau Optimization (AMI)",
                module="edm_tau_optimization", function="optimal_tau",
                mandatory=False,
                rationale="AMI-based optimal delay. Skip if data too short."))

        # Step 4: EDM embedding + nonlinearity (if goal requires)
        if self.goal in (AnalysisGoal.DETECT_NONLINEARITY,
                         AnalysisGoal.EXPLORE,
                         AnalysisGoal.PREDICT):
            step_order += 1
            plan.steps.append(RouteStep(
                order=step_order, name="EDM Embedding + S-Map",
                module="edm_adaptive_pipeline", function="run_adaptive_edm",
                mandatory=True,
                rationale="Embedding dimension + nonlinearity detection."))

        # Step 5: HAVOK decomposition (if goal is phase or explore, and N>=50)
        if (self.goal in (AnalysisGoal.PHASE_TRANSITION, AnalysisGoal.EXPLORE)
                and self.n >= 30):
            step_order += 1
            mandatory_havok = (self.goal == AnalysisGoal.PHASE_TRANSITION)
            plan.steps.append(RouteStep(
                order=step_order, name="HAVOK Decomposition",
                module="sovereign_havok", function="SovereignHAVOK.fit",
                mandatory=mandatory_havok,
                rationale="Koopman operator + forcing term analysis."))

        # Step 6: Surrogate test (if detecting nonlinearity)
        if self.goal in (AnalysisGoal.DETECT_NONLINEARITY,
                         AnalysisGoal.CAUSAL_INFERENCE):
            step_order += 1
            plan.steps.append(RouteStep(
                order=step_order, name="IAAFT Surrogate Test",
                module="surrogate_test", function="havok_surrogate_check",
                mandatory=(grade == DataGrade.MARGINAL),
                args={"n_surrogates": 99 if grade == DataGrade.EXCELLENT else 19},
                rationale="Mandatory before believing any nonlinear metric."))

        # Step 7: CCM causality (if goal is causal)
        if self.goal == AnalysisGoal.CAUSAL_INFERENCE and self.n_vars >= 2:
            step_order += 1
            plan.steps.append(RouteStep(
                order=step_order, name="CCM Causality (Victim Mirror)",
                module="final_interpretation", function="ccm_with_convergence",
                mandatory=True,
                rationale="Causal direction + convergence slope check. "
                          "Secret 11's disclaimer is included automatically "
                          "in every ccm_causality_test() result — no "
                          "separate step needed."))

            # Secret 10: Seasonality/Periodic-Forcing Confound — reference
            # doc: `if n>=20 and ccm_will_run: active.append(S10)`.
            if self.n >= 20:
                step_order += 1
                plan.steps.append(RouteStep(
                    order=step_order, name="Seasonality Confound Check",
                    module="edm_auditor", function="audit_seasonality_confound",
                    mandatory=False,
                    rationale="Secret 10: shared periodic driver can make "
                              "CCM report spurious convergent 'causality'. "
                              "Needs named multi-variable data + the CCM "
                              "pairs actually tested, so this step is not "
                              "generically auto-executable — see it as a "
                              "recorded recommendation, run "
                              "audit_seasonality_confound() directly with "
                              "your data_dict and CCM pairs."))

            # Secret 13: Multiple Comparison Correction — reference doc:
            # `if ccm_pairs >= 5: active.append(S13)`. Below 5 pairs the
            # family-wise error inflation is modest enough that
            # ccm_causality_test()'s per-pair convergence check (already
            # mandatory, step above) is considered sufficient without a
            # separate correction step — see thresholds_and_heuristics.md.
            if self.ccm_pairs >= 5:
                step_order += 1
                plan.steps.append(RouteStep(
                    order=step_order, name="Multi-Comparison Correction (CCM)",
                    module="ccm_causality", function="ccm_batch_test",
                    mandatory=True,
                    rationale=f"Secret 13: {self.ccm_pairs} pairwise CCM "
                              f"tests planned — uncorrected family-wise "
                              f"false-positive risk is "
                              f"~{1 - (1 - 0.05) ** self.ccm_pairs:.0%}. "
                              f"Use Bonferroni if pre-registered, "
                              f"Benjamini-Hochberg FDR otherwise."))

        # Secret 12: Prediction Decay Profile Analysis — reference doc:
        # `if n>=30 and goal in ['predict','detect_nl']: active.append(S12)`.
        if self.n >= 30 and self.goal in (AnalysisGoal.PREDICT,
                                          AnalysisGoal.DETECT_NONLINEARITY):
            step_order += 1
            plan.steps.append(RouteStep(
                order=step_order, name="Decay Profile Scan",
                module="sensitivity_config", function="decay_profile_scan",
                mandatory=False,
                rationale="Secret 12: classify rho(Tp) decay shape "
                          "(exponential/flat/cutoff/oscillatory); cross-"
                          "checks against Secret 1's Lyapunov estimate "
                          "when available."))

        # Note on Secrets not requiring a separate RouteStep:
        #   S8 (Stationarity) and S9 (Observation Genericity) run
        #     automatically inside step 2's audit_pipeline() call whenever
        #     `data` is supplied (route_and_execute always supplies it —
        #     see _call_step's data-keyword injection rule, Round 11).
        #   S11 (Common Driver Disclaimer) is unconditional inside
        #     ccm_causality_test() itself — every CCM result carries it.
        #   S14 (Sampling Adequacy) runs automatically inside
        #     SovereignHAVOK.fit() (step 5) via _check_sampling_adequacy(),
        #     populating sh.sampling_adequacy_ — no separate step needed.

        # Step 8: Sensitivity scan (if any E was chosen)
        if any('Embedding' in s.name for s in plan.steps):
            step_order += 1
            plan.steps.append(RouteStep(
                order=step_order, name="Sensitivity Scan (E+/-1)",
                module="sensitivity_config", function="sensitivity_scan",
                mandatory=False,
                rationale="Check if conclusion survives parameter perturbation."))

        # Step 9: Config artifact (always, as last step)
        step_order += 1
        plan.steps.append(RouteStep(
            order=step_order, name="Save Analysis Config",
            module="sensitivity_config", function="save_config",
            mandatory=True,
            rationale="Timestamped JSON artifact for reproducibility."))

        return plan


# ── Convenience wrappers ──────────────────────────────────

def quick_route(n_samples: int, **kwargs) -> AnalysisPlan:
    """One-shot routing. Returns AnalysisPlan."""
    return Router(n_samples=n_samples, **kwargs).route()


def _resolve_step_callable(mod, function: str):
    """
    Resolve a possibly-dotted function path (e.g. 'SovereignHAVOK.fit') to
    a callable, handling the case where the leaf is an unbound instance
    method by instantiating the class first (only works for classes whose
    constructor is default-constructible, i.e. all-keyword-with-defaults).

    Returns (callable, was_instantiated). Raises AttributeError/TypeError
    on failure, same as a plain getattr chain would — callers catch these.
    """
    parts = function.split('.')
    obj = getattr(mod, parts[0])
    if len(parts) == 1:
        return obj, False
    if inspect.isclass(obj):
        instance = obj()  # may raise TypeError if not default-constructible
        target = instance
        for p in parts[1:]:
            target = getattr(target, p)
        return target, True
    target = obj
    for p in parts[1:]:
        target = getattr(target, p)
    return target, False


def _call_step(fn, data, step_args: Dict):
    """
    Call a resolved step function, injecting `data` where it clearly
    belongs, and raising a clear, distinguishable error when the function
    needs more context than the router has available — rather than
    letting a bare "missing N required positional arguments" TypeError
    surface as if something were broken.

    Injection rules (in order):
      1. If `data` is available and the function has exactly one required
         (no-default) positional parameter that step_args does not
         already supply, pass `data` there.
      2. Otherwise, if the function has an *optional* keyword parameter
         literally named `data` that step_args does not already set,
         pass `data=data` there too. This second rule exists because a
         function can be fully auto-executable in spirit — every
         parameter has a sensible default — while still behaving
         materially differently when `data` is supplied (e.g.
         `edm_auditor.audit_pipeline(data=None, n=None, ...)`: every
         parameter is optional, so rule 1 never fires for it, but without
         `data` specifically, Secret 8 (Stationarity) and Secret 9
         (Observation Genericity) — both of which only run when raw data
         is available — silently never execute even though the function
         call itself "succeeds". Confirmed via this module's own
         self-test: the "Configuration Audit" step ran without error but
         never actually exercised S8/S9 until this rule was added. See
         docs/CHANGELOG.md (Round 11).
      Rule 2 is deliberately narrow (exact parameter name `data`, not a
      guess at any array-like-sounding name) to avoid silently injecting
      into the wrong keyword of some other function.

    This deliberately does NOT attempt to guess values for functions
    needing MORE required parameters than `data` alone can satisfy (e.g.
    `run_adaptive_edm(df, target_col)` needs a column name the router has
    no way to know; `sensitivity_scan(data, base_E, metric_fn)` needs a
    callable metric function) — those are reported as
    NOT_AUTO_EXECUTABLE rather than silently guessed at.
    """
    sig = inspect.signature(fn)
    required = [
        p for p in sig.parameters.values()
        if p.default is inspect.Parameter.empty
        and p.kind in (inspect.Parameter.POSITIONAL_ONLY,
                       inspect.Parameter.POSITIONAL_OR_KEYWORD)
        and p.name not in step_args
    ]
    if len(required) == 1 and data is not None:
        return fn(data, **step_args)
    if len(required) == 0:
        if (data is not None and 'data' in sig.parameters
                and 'data' not in step_args):
            return fn(data=data, **step_args)
        return fn(**step_args)
    missing = [p.name for p in required]
    raise NotAutoExecutableError(
        f"needs {missing} beyond what the router plan can supply "
        f"generically (data={'available' if data is not None else 'None'}). "
        f"This step is a real, correct part of the analysis — it just "
        f"needs richer context (a DataFrame + column name, a metric "
        f"function, etc.) than a routing decision can encode generically. "
        f"Run it directly, or use pipeline.run_full_analysis() which wires "
        f"this exact context through correctly.")


class NotAutoExecutableError(Exception):
    """Raised when a step's function needs more context than the generic
    router executor can supply (see _call_step). Distinguishes "this step
    is real and correct, just not genuinely auto-runnable from a routing
    decision alone" from an actual broken/unresolvable step."""
    pass


def route_and_execute(n_samples: int, data=None, **kwargs) -> Dict:
    """
    Route AND execute the plan automatically (Garden of Forking Paths
    countermeasure: no manual parameter fiddling between route and execute).

    Honest scope note: this generically auto-executes steps whose function
    needs nothing beyond `data` plus the plan's own `step.args` (e.g.
    Environment Validation, Configuration Audit, Tau Optimization, HAVOK
    Decomposition). Steps that need richer context a routing decision
    can't encode generically — a target column name, a metric callable,
    an upstream config object — are reported as NOT_AUTO_EXECUTABLE with
    an explanation, not silently mis-run or hidden behind a raw TypeError.
    For the full, correctly-wired numerical pipeline (each stage's output
    threaded into the next), use `pipeline.run_full_analysis()` instead;
    this function's job is the routing/gating decision, not full
    orchestration — see docs/CHANGELOG.md (Round 10) for why this
    distinction matters and what used to be broken here.

    Returns dict with plan, results, and config artifact path.
    """
    router = Router(n_samples=n_samples, **kwargs)
    plan = router.route()

    if plan.blocks:
        plan.print_plan()
        return {"plan": plan, "results": None, "blocked": True}

    plan.print_plan()

    # Auto-execute each step. step.function may be a dotted path like
    # "SovereignHAVOK.fit" (class.method) — _resolve_step_callable handles
    # instantiating the class first. _call_step injects `data` only when
    # it unambiguously belongs (exactly one missing required parameter);
    # steps needing more are reported as NOT_AUTO_EXECUTABLE rather than
    # crashing the whole plan or being silently misreported as a generic
    # SKIP (see docstring above and docs/CHANGELOG.md, Round 10 — this
    # used to be dead code: `'data' in step.args` was always False because
    # no RouteStep ever actually put 'data' in its args, so every step
    # needing data silently failed even when `data` was supplied).
    results = {}
    for step in plan.steps:
        try:
            mod = __import__(step.module, fromlist=['*'])
            fn, _ = _resolve_step_callable(mod, step.function)
            result = _call_step(fn, data, step.args)
            results[step.name] = "OK" if result is not None else "executed"
        except NotAutoExecutableError as e:
            results[step.name] = f"NOT_AUTO_EXECUTABLE: {e}"
        except Exception as e:
            results[step.name] = f"SKIP: {type(e).__name__}: {e}"
            # Do not break on SKIP — only break on mandatory step hard errors.
            # A missing callable is a planning/contract issue, not a data issue.

    # Save config. This duplicates what the "Save Analysis Config" RouteStep
    # would do if it were generically auto-executable (it isn't — save_config
    # needs the `config` object produced by capture_config, not raw data),
    # so if that step exists in the plan, reflect the REAL outcome here
    # instead of leaving its entry stuck at a generic SKIP/NOT_AUTO_EXECUTABLE
    # message that would misleadingly suggest the config was never saved.
    from sensitivity_config import capture_config, save_config
    cfg = capture_config(data, analysis_type=plan.label.value)
    config_path = save_config(cfg, f"results/config_{int(time.time())}.json")
    if any(s.name == "Save Analysis Config" for s in plan.steps):
        results["Save Analysis Config"] = f"OK: {config_path}"

    return {
        "plan": plan,
        "results": results,
        "config_path": config_path,
        "blocked": False,
    }


# ── Self-test ─────────────────────────────────────────────

if __name__ == '__main__':
    print("=" * 64)
    print("  Router Self-Test — Decision Triage Channel")
    print("=" * 64)

    # Scenario A: Game data (32 samples, binary target, goal=explore)
    print("\n── Scenario A: Game data (N=32, binary, goal=explore) ──")
    plan_a = quick_route(n_samples=32, n_variables=4, is_binary_target=True,
                         goal="explore")
    plan_a.print_plan()
    assert plan_a.data_grade == DataGrade.MARGINAL
    assert plan_a.label == AnalysisLabel.EXPLORATORY
    assert len(plan_a.warnings) >= 2  # binary + Multiview + no prereg
    assert len(plan_a.blocks) == 0
    print("  [OK] Correctly graded MARGINAL, no blocks, with warnings")

    # Scenario B: Large dataset (500 samples, goal=phase)
    print("\n── Scenario B: Large dataset (N=500, goal=phase) ──")
    plan_b = quick_route(n_samples=500, n_variables=2, goal="phase",
                         has_preregistration=True)
    plan_b.print_plan()
    assert plan_b.data_grade == DataGrade.EXCELLENT
    assert plan_b.label == AnalysisLabel.CONFIRMATORY
    assert any('HAVOK' in s.name for s in plan_b.steps)
    print("  [OK] EXCELLENT grade, CONFIRMATORY, HAVOK included")

    # Scenario C: Tiny dataset (15 samples)
    print("\n── Scenario C: Tiny dataset (N=15) ──")
    plan_c = quick_route(n_samples=15)
    plan_c.print_plan()
    assert plan_c.data_grade == DataGrade.INADEQUATE
    assert len(plan_c.blocks) >= 1
    assert "Bayesian" in plan_c.blocks[0]
    print("  [OK] BLOCKED — correctly routes away from EDM/HAVOK")

    # Scenario D: Causal inference (100 samples, 3 vars)
    print("\n── Scenario D: Causal inference (N=100, 3 vars) ──")
    plan_d = quick_route(n_samples=100, n_variables=3, goal="causal")
    plan_d.print_plan()
    assert any('CCM' in s.name for s in plan_d.steps)
    assert any('Surrogate' in s.name for s in plan_d.steps)
    print("  [OK] CCM + surrogate test both included")

    # Scenario E: Predict with marginal data (should block)
    print("\n── Scenario E: Predict with marginal data (should block) ──")
    plan_e = quick_route(n_samples=30, is_regular=False, goal="predict")
    plan_e.print_plan()
    assert len(plan_e.blocks) >= 1
    print("  [OK] BLOCKED prediction on irregular data")

    # Scenario F: Serialization
    print("\n── Scenario F: Plan serialization ──")
    d = plan_a.to_dict()
    assert 'data_grade' in d
    assert 'steps' in d
    assert len(d['steps']) >= 3
    print(f"  [OK] Plan serialized: {len(d['steps'])} steps, "
          f"grade={d['data_grade']}, label={d['label']}")

    # Scenario G: route_and_execute — actually runs the plan.
    # Before Round 10 this was completely untested (no call site anywhere
    # in the codebase), and was in fact broken: `data` was never wired
    # into any step's arguments (the `'data' in step.args` check was dead
    # code — no RouteStep ever populated that key), so every step needing
    # data failed and was silently mis-reported as a generic SKIP. See
    # docs/CHANGELOG.md (Round 10).
    print("\n── Scenario G: route_and_execute (actually runs steps) ──")
    import numpy as np
    np.random.seed(0)
    data_g = np.cumsum(np.random.randn(60)) + np.sin(np.linspace(0, 10, 60)) * 3
    result_g = route_and_execute(n_samples=60, data=data_g,
                                 n_variables=1, goal="explore")
    assert result_g["blocked"] is False
    # Steps that need only `data` (+ the plan's own args) must actually run.
    assert result_g["results"]["Environment Validation"] == "OK"
    assert result_g["results"]["Configuration Audit"] == "OK"
    assert result_g["results"]["Tau Optimization (AMI)"] == "OK", (
        "optimal_tau(series) needs only `data` — must auto-execute, not SKIP")
    # Steps needing context the router can't supply generically must be
    # reported as such, not silently misreported as a data/wiring failure.
    assert result_g["results"]["EDM Embedding + S-Map"].startswith("NOT_AUTO_EXECUTABLE")
    # Config must actually be saved, and the step's own result entry must
    # reflect that (not a leftover generic SKIP).
    assert result_g["results"]["Save Analysis Config"].startswith("OK:")
    assert result_g["config_path"] is not None
    print(f"  [OK] Environment/Audit/Tau steps genuinely executed (not SKIPped)")
    print(f"  [OK] Multi-arg steps honestly report NOT_AUTO_EXECUTABLE")
    print(f"  [OK] Config saved and reflected in results: {result_g['config_path']}")

    # Scenario G2: `_call_step`'s keyword-injection rule (Round 11).
    # `audit_pipeline`-shaped functions (every parameter optional, but one
    # of them is literally named `data`) are NOT caught by the "exactly
    # one required positional parameter" rule (rule 1), since they have
    # ZERO required parameters — so without a second rule, `data` would
    # never reach them even though the function meaningfully depends on
    # it (Secret 8/9 only run when `data` is actually supplied). This
    # regression-tests that second rule directly.
    print("\n── Scenario G2: _call_step data-keyword injection (Round 11) ──")

    def _fn_all_optional_with_data_kwarg(data=None, n=None, flag=False):
        return {"got_data": data is not None, "n": n}

    r_g2a = _call_step(_fn_all_optional_with_data_kwarg, data_g, {"n": 60})
    assert r_g2a["got_data"] is True, (
        "a function with zero required params but a `data` keyword must "
        "still receive `data` when available")
    print("  [OK] data injected into an all-optional function via its `data` keyword")

    def _fn_all_optional_no_data_kwarg(x=None, n=None):
        return {"x": x, "n": n}

    r_g2b = _call_step(_fn_all_optional_no_data_kwarg, data_g, {"n": 60})
    assert r_g2b["x"] is None, (
        "a function with no `data`-named keyword must NOT have `data` "
        "guessed into some other keyword")
    print("  [OK] data NOT guessed into an unrelated keyword when no `data` param exists")

    # Confirm this actually reaches Secret 8/9 through the real
    # audit_pipeline (not just the synthetic stand-in above).
    from edm_auditor import audit_pipeline
    report_g2 = _call_step(audit_pipeline, data_g, {"n": 60, "is_binary": False})
    s8_finding = next(f for f in report_g2.findings if "Secret 8" in f.secret_ref)
    s9_finding = next(f for f in report_g2.findings if "Secret 9" in f.secret_ref)
    assert s8_finding.status != "SKIP", (
        "Secret 8 must actually run (not SKIP for missing data) when "
        "route_and_execute calls audit_pipeline with real data available")
    assert s9_finding.status != "SKIP"
    print("  [OK] audit_pipeline (called the way route_and_execute calls it) "
          "actually runs Secret 8 and Secret 9, not just returns OK vacuously")

    print("\n" + "=" * 64)
    print("  Router: ALL SCENARIOS PASSED")
    print("=" * 64)
