// This file is auto-generated by generate-pdf-data.js

const pdfFiles = [
    {
        "title": "人偶之匣（魔女的盒子）",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Miscellanies/%E4%BA%BA%E5%81%B6%E4%B9%8B%E5%8C%A3%EF%BC%88%E9%AD%94%E5%A5%B3%E7%9A%84%E7%9B%92%E5%AD%90%EF%BC%89.pdf",
        "localFile": "Miscellanies/人偶之匣（魔女的盒子）.pdf"
    },
    {
        "title": "元皇经",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Miscellanies/%E5%85%83%E7%9A%87%E7%BB%8F.pdf",
        "localFile": "Miscellanies/元皇经.pdf"
    },
    {
        "title": "太易 - 太伊原枢（纪录）",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Miscellanies/%E5%A4%AA%E6%98%93%20-%20%E5%A4%AA%E4%BC%8A%E5%8E%9F%E6%9E%A2%EF%BC%88%E7%BA%AA%E5%BD%95%EF%BC%89.pdf",
        "localFile": "Miscellanies/太易 - 太伊原枢（纪录）.pdf"
    },
    {
        "title": "太易神式(0.9)",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Miscellanies/%E5%A4%AA%E6%98%93%E7%A5%9E%E5%BC%8F(0.9).pdf",
        "localFile": "Miscellanies/太易神式(0.9).pdf"
    },
    {
        "title": "歌剧（HYPER-PLOY）",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Miscellanies/%E6%AD%8C%E5%89%A7%EF%BC%88HYPER-PLOY%EF%BC%89.pdf",
        "localFile": "Miscellanies/歌剧（HYPER-PLOY）.pdf"
    },
    {
        "title": "比尔斯书（奥利巴喀）",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Miscellanies/%E6%AF%94%E5%B0%94%E6%96%AF%E4%B9%A6%EF%BC%88%E5%A5%A5%E5%88%A9%E5%B7%B4%E5%96%80%EF%BC%89.pdf",
        "localFile": "Miscellanies/比尔斯书（奥利巴喀）.pdf"
    },
    {
        "title": "源始",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Miscellanies/%E6%BA%90%E5%A7%8B.pdf",
        "localFile": "Miscellanies/源始.pdf"
    },
    {
        "title": "皇匮",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Miscellanies/%E7%9A%87%E5%8C%AE.pdf",
        "localFile": "Miscellanies/皇匮.pdf"
    },
    {
        "title": "Annals-of-the-Great-Simplicity",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Core-Magician/Annals-of-the-Great-Simplicity.pdf",
        "localFile": "Miscellanies/Annals-of-the-Great-Simplicity.pdf"
    },
    {
        "title": "Annals-of-the-Great-Simplicity2",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Core-Magician/Annals-of-the-Great-Simplicity2.pdf",
        "localFile": "Miscellanies/Annals-of-the-Great-Simplicity2.pdf"
    },
    {
        "title": "专题报告",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Core-Magician/%E4%B8%93%E9%A2%98%E6%8A%A5%E5%91%8A.pdf",
        "localFile": "Miscellanies/专题报告.pdf"
    },
    {
        "title": "太易·法由藏",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Core-Magician/%E5%A4%AA%E6%98%93%C2%B7%E6%B3%95%E7%94%B1%E8%97%8F.pdf",
        "localFile": "Miscellanies/太易·法由藏.pdf"
    },
    {
        "title": "太皇玄经（素帛）",
        "remoteFile": "https://raw.githubusercontent.com/SAY683/Annals-of-the-Great-Simplicity/8cc877c11d30e7b0f067a97ac10aadb41a4c509e/Core-Magician/%E5%A4%AA%E7%9A%87%E7%8E%84%E7%BB%8F%EF%BC%88%E7%B4%A0%E5%B8%9B%EF%BC%89.pdf",
        "localFile": "Miscellanies/太皇玄经（素帛）.pdf"
    }
];