"""
EDM-Takens Skill Router — Decision Triage Channel
===================================================
Deterministic decision flow that routes any time-series analysis
request through the correct methodology path.

Design principle (Garden of Forking Paths countermeasure):
  All decisions are automated, not hand-tuned. The router closes the
  "try parameters until something looks significant" loophole by
  encoding every decision as a fixed rule before any computation runs.

Usage:
  from router import Router
  router = Router(data, n_variables=4, is_binary=True)
  plan = router.route()
  plan.print_plan()
  plan.execute()  # runs the full path

The router answers five questions in strict order:
  Q1: Is this data suitable for EDM/HAVOK at all?
  Q2: Which specific methods should run?
  Q3: What parameters? (auto-detected, not hand-tuned)
  Q4: What validations are MANDATORY vs optional?
  Q5: What is the output labeling? (exploratory/confirmatory)
"""

import os, sys, json, time
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Tuple
from enum import Enum


# ── Type definitions ──────────────────────────────────────

class DataGrade(Enum):
    """Data quality tier — determines which method family is viable."""
    EXCELLENT = "excellent"   # N>=100, regular, clean → full pipeline
    ADEQUATE = "adequate"     # N>=50, regular, moderate noise → with surrogates
    MARGINAL = "marginal"     # N<50 or irregular → limited methods, strong warnings
    INADEQUATE = "inadequate" # N<20 or very noisy → do NOT use EDM/HAVOK


class AnalysisGoal(Enum):
    """What the user wants to achieve."""
    PREDICT = "predict"                # out-of-sample forecasting
    DETECT_NONLINEARITY = "detect_nl"  # is the system nonlinear?
    CAUSAL_INFERENCE = "causal"        # what drives what?
    PHASE_TRANSITION = "phase"         # when do regime shifts occur?
    EXPLORE = "explore"               # generate hypotheses


class AnalysisLabel(Enum):
    """Output labeling requirement (research-rigor.md principle 7)."""
    EXPLORATORY = "exploratory"    # hypothesis-generating, NOT confirmatory
    CONFIRMATORY = "confirmatory"  # pre-registered, p-value valid


@dataclass
class RouteStep:
    """One step in the execution plan."""
    order: int
    name: str
    module: str           # Python module to call
    function: str         # function name
    mandatory: bool       # can this be skipped?
    args: Dict = field(default_factory=dict)
    rationale: str = ""


@dataclass
class AnalysisPlan:
    """Complete analysis plan generated by the Router."""
    data_grade: DataGrade
    goal: AnalysisGoal
    label: AnalysisLabel
    steps: List[RouteStep] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    blocks: List[str] = field(default_factory=list)

    def print_plan(self):
        """Human-readable plan output."""
        print("\n" + "=" * 64)
        print(f"  ANALYSIS PLAN")
        print(f"  Data Grade: {self.data_grade.value.upper()}")
        print(f"  Goal:       {self.goal.value}")
        print(f"  Label:      {self.label.value.upper()}")
        print("=" * 64)

        if self.blocks:
            print(f"\n  !! BLOCKED ({len(self.blocks)} issues):")
            for b in self.blocks:
                print(f"     [XX] {b}")
            print(f"  => DO NOT PROCEED. Fix blockers before retrying.")

        if self.warnings:
            print(f"\n  !! WARNINGS ({len(self.warnings)}):")
            for w in self.warnings:
                print(f"     [!] {w}")

        if self.steps:
            print(f"\n  EXECUTION PLAN ({len(self.steps)} steps):")
            for s in self.steps:
                tag = "[REQUIRED]" if s.mandatory else "[optional]"
                print(f"  {s.order:2d}. {tag} {s.name}")
                print(f"      → {s.module}.{s.function}()")
                if s.rationale:
                    print(f"      {s.rationale[:70]}")

    def to_dict(self) -> Dict:
        """Serialize plan to dict (for JSON config artifact)."""
        return {
            'data_grade': self.data_grade.value,
            'goal': self.goal.value,
            'label': self.label.value,
            'steps': [{'order': s.order, 'name': s.name,
                       'module': s.module, 'function': s.function,
                       'mandatory': s.mandatory, 'rationale': s.rationale}
                      for s in self.steps],
            'warnings': self.warnings,
            'blocks': self.blocks,
            'timestamp': time.strftime('%Y-%m-%dT%H:%M:%S'),
        }


# ── Router ────────────────────────────────────────────────

class Router:
    """
    Deterministic routing engine for EDM/HAVOK analysis.

    Takes data characteristics → outputs executable plan.
    Every decision is rule-based (no parameter-hopping).
    """

    def __init__(self,
                 n_samples: int,
                 n_variables: int = 1,
                 is_regular: bool = True,
                 is_binary_target: bool = False,
                 snr_estimate: Optional[str] = None,
                 goal: str = "explore",
                 has_preregistration: bool = False):
        """
        Parameters
        ----------
        n_samples : int
            Number of time points.
        n_variables : int
            Number of measured variables (columns).
        is_regular : bool
            Is sampling interval uniform?
        is_binary_target : bool
            Is the target variable 0/1 (binary)?
        snr_estimate : str, optional
            "high", "moderate", "low", or None (unknown).
        goal : str
            "predict", "detect_nl", "causal", "phase", "explore"
        has_preregistration : bool
            Has a pre-registration document been written?
        """
        self.n = n_samples
        self.n_vars = n_variables
        self.is_regular = is_regular
        self.is_binary = is_binary_target
        self.snr = snr_estimate or "unknown"
        self.has_prereg = has_preregistration

        goal_map = {
            "predict": AnalysisGoal.PREDICT,
            "detect_nl": AnalysisGoal.DETECT_NONLINEARITY,
            "causal": AnalysisGoal.CAUSAL_INFERENCE,
            "phase": AnalysisGoal.PHASE_TRANSITION,
            "explore": AnalysisGoal.EXPLORE,
        }
        self.goal = goal_map.get(goal, AnalysisGoal.EXPLORE)

    # ── Q1: Data grading ──────────────────────────────────

    def _grade_data(self) -> DataGrade:
        """Determine data quality tier."""
        if self.n < 20:
            return DataGrade.INADEQUATE
        if not self.is_regular:
            return DataGrade.MARGINAL
        if self.snr == "low":
            return DataGrade.MARGINAL

        if self.n >= 100 and self.snr in ("high", "moderate", "unknown"):
            return DataGrade.EXCELLENT
        elif self.n >= 50:
            return DataGrade.ADEQUATE
        else:
            return DataGrade.MARGINAL

    # ── Q2-Q5: Build plan ─────────────────────────────────

    def route(self) -> AnalysisPlan:
        """Execute the full routing logic. Returns AnalysisPlan."""
        grade = self._grade_data()
        label = (AnalysisLabel.CONFIRMATORY if self.has_prereg
                 else AnalysisLabel.EXPLORATORY)

        plan = AnalysisPlan(data_grade=grade, goal=self.goal, label=label)

        # ── Blockers ──
        if grade == DataGrade.INADEQUATE:
            plan.blocks.append(
                f"N={self.n} is below minimum (20). "
                f"EDM/HAVOK cannot reliably reconstruct an attractor. "
                f"Switch to Bayesian state-space models or Gaussian processes.")
            return plan

        if self.goal == AnalysisGoal.PREDICT and grade == DataGrade.MARGINAL:
            plan.blocks.append(
                f"Prediction requested but N={self.n} with "
                f"irregular/noisy data cannot support out-of-sample forecasting. "
                f"Downgrade goal to 'explore' or collect more data.")

        if self.goal == AnalysisGoal.PHASE_TRANSITION and self.n < 100:
            plan.warnings.append(
                f"Phase transition detection needs N>=100 for reliable "
                f"kurtosis estimation. Results will be SUGGESTIVE only.")

        # ── Warnings ──
        if self.is_binary:
            plan.warnings.append(
                "Binary target: EDM rho ceiling ~0.87. "
                "Prefer continuous covariates for attractor reconstruction.")

        if self.n_vars >= 3 and self.n < 100:
            plan.warnings.append(
                f"Multiview embedding recommended (N={self.n}<100, "
                f"K={self.n_vars} variables). Saves data-efficiency loss.")

        if label == AnalysisLabel.EXPLORATORY:
            plan.warnings.append(
                "No pre-registration detected. Results will be labeled "
                "EXPLORATORY. Do not use confirmatory language.")

        # ── Build step sequence ──
        step_order = 0

        # Step 1: Environment (always)
        step_order += 1
        plan.steps.append(RouteStep(
            order=step_order, name="Environment Validation",
            module="environment_check", function="validate_environment",
            mandatory=True,
            rationale="Verify all dependencies before any computation."))

        # Step 2: Auditor (always)
        step_order += 1
        plan.steps.append(RouteStep(
            order=step_order, name="Configuration Audit",
            module="edm_auditor", function="audit_pipeline",
            mandatory=True,
            args={"n": self.n, "is_binary": self.is_binary},
            rationale="Firewall: block invalid configs before computation."))

        # Step 3: Tau optimization (if applicable)
        if self.n >= 30:
            step_order += 1
            plan.steps.append(RouteStep(
                order=step_order, name="Tau Optimization (AMI)",
                module="edm_tau_optimization", function="optimal_tau",
                mandatory=False,
                rationale="AMI-based optimal delay. Skip if data too short."))

        # Step 4: EDM embedding + nonlinearity (if goal requires)
        if self.goal in (AnalysisGoal.DETECT_NONLINEARITY,
                         AnalysisGoal.EXPLORE,
                         AnalysisGoal.PREDICT):
            step_order += 1
            plan.steps.append(RouteStep(
                order=step_order, name="EDM Embedding + S-Map",
                module="edm_adaptive_pipeline", function="run_adaptive_edm",
                mandatory=True,
                rationale="Embedding dimension + nonlinearity detection."))

        # Step 5: HAVOK decomposition (if goal is phase or explore, and N>=50)
        if (self.goal in (AnalysisGoal.PHASE_TRANSITION, AnalysisGoal.EXPLORE)
                and self.n >= 30):
            step_order += 1
            mandatory_havok = (self.goal == AnalysisGoal.PHASE_TRANSITION)
            plan.steps.append(RouteStep(
                order=step_order, name="HAVOK Decomposition",
                module="sovereign_havok", function="SovereignHAVOK.fit",
                mandatory=mandatory_havok,
                rationale="Koopman operator + forcing term analysis."))

        # Step 6: Surrogate test (if detecting nonlinearity)
        if self.goal in (AnalysisGoal.DETECT_NONLINEARITY,
                         AnalysisGoal.CAUSAL_INFERENCE):
            step_order += 1
            plan.steps.append(RouteStep(
                order=step_order, name="IAAFT Surrogate Test",
                module="surrogate_test", function="havok_surrogate_check",
                mandatory=(grade == DataGrade.MARGINAL),
                args={"n_surrogates": 99 if grade == DataGrade.EXCELLENT else 19},
                rationale="Mandatory before believing any nonlinear metric."))

        # Step 7: CCM causality (if goal is causal)
        if self.goal == AnalysisGoal.CAUSAL_INFERENCE and self.n_vars >= 2:
            step_order += 1
            plan.steps.append(RouteStep(
                order=step_order, name="CCM Causality (Victim Mirror)",
                module="final_interpretation", function="ccm_with_convergence",
                mandatory=True,
                rationale="Causal direction + convergence slope check."))

        # Step 8: Sensitivity scan (if any E was chosen)
        if any('Embedding' in s.name for s in plan.steps):
            step_order += 1
            plan.steps.append(RouteStep(
                order=step_order, name="Sensitivity Scan (E+/-1)",
                module="sensitivity_config", function="sensitivity_scan",
                mandatory=False,
                rationale="Check if conclusion survives parameter perturbation."))

        # Step 9: Config artifact (always, as last step)
        step_order += 1
        plan.steps.append(RouteStep(
            order=step_order, name="Save Analysis Config",
            module="sensitivity_config", function="save_config",
            mandatory=True,
            rationale="Timestamped JSON artifact for reproducibility."))

        return plan


# ── Convenience wrappers ──────────────────────────────────

def quick_route(n_samples: int, **kwargs) -> AnalysisPlan:
    """One-shot routing. Returns AnalysisPlan."""
    return Router(n_samples=n_samples, **kwargs).route()


def route_and_execute(n_samples: int, data=None, **kwargs) -> Dict:
    """
    Route AND execute the plan automatically (Garden of Forking Paths
    countermeasure: no manual parameter fiddling between route and execute).

    Returns dict with plan, results, and config artifact path.
    """
    router = Router(n_samples=n_samples, **kwargs)
    plan = router.route()

    if plan.blocks:
        plan.print_plan()
        return {"plan": plan, "results": None, "blocked": True}

    plan.print_plan()

    # Auto-execute each step
    results = {}
    for step in plan.steps:
        try:
            mod = __import__(step.module, fromlist=[step.function])
            fn = getattr(mod, step.function)
            if data is not None and 'data' in step.args:
                result = fn(data, **{k: v for k, v in step.args.items()
                                     if k != 'data'})
            else:
                result = fn(**step.args)
            results[step.name] = "OK" if result is not None else "executed"
        except Exception as e:
            results[step.name] = f"ERROR: {e}"
            if step.mandatory:
                break

    # Save config
    from sensitivity_config import capture_config, save_config
    cfg = capture_config(data, analysis_type=plan.label.value)
    config_path = save_config(cfg, f"results/config_{int(time.time())}.json")

    return {
        "plan": plan,
        "results": results,
        "config_path": config_path,
        "blocked": False,
    }


# ── Self-test ─────────────────────────────────────────────

if __name__ == '__main__':
    print("=" * 64)
    print("  Router Self-Test — Decision Triage Channel")
    print("=" * 64)

    # Scenario A: Game data (32 samples, binary target, goal=explore)
    print("\n── Scenario A: Game data (N=32, binary, goal=explore) ──")
    plan_a = quick_route(n_samples=32, n_variables=4, is_binary_target=True,
                         goal="explore")
    plan_a.print_plan()
    assert plan_a.data_grade == DataGrade.MARGINAL
    assert plan_a.label == AnalysisLabel.EXPLORATORY
    assert len(plan_a.warnings) >= 2  # binary + Multiview + no prereg
    assert len(plan_a.blocks) == 0
    print("  [OK] Correctly graded MARGINAL, no blocks, with warnings")

    # Scenario B: Large dataset (500 samples, goal=phase)
    print("\n── Scenario B: Large dataset (N=500, goal=phase) ──")
    plan_b = quick_route(n_samples=500, n_variables=2, goal="phase",
                         has_preregistration=True)
    plan_b.print_plan()
    assert plan_b.data_grade == DataGrade.EXCELLENT
    assert plan_b.label == AnalysisLabel.CONFIRMATORY
    assert any('HAVOK' in s.name for s in plan_b.steps)
    print("  [OK] EXCELLENT grade, CONFIRMATORY, HAVOK included")

    # Scenario C: Tiny dataset (15 samples)
    print("\n── Scenario C: Tiny dataset (N=15) ──")
    plan_c = quick_route(n_samples=15)
    plan_c.print_plan()
    assert plan_c.data_grade == DataGrade.INADEQUATE
    assert len(plan_c.blocks) >= 1
    assert "Bayesian" in plan_c.blocks[0]
    print("  [OK] BLOCKED — correctly routes away from EDM/HAVOK")

    # Scenario D: Causal inference (100 samples, 3 vars)
    print("\n── Scenario D: Causal inference (N=100, 3 vars) ──")
    plan_d = quick_route(n_samples=100, n_variables=3, goal="causal")
    plan_d.print_plan()
    assert any('CCM' in s.name for s in plan_d.steps)
    assert any('Surrogate' in s.name for s in plan_d.steps)
    print("  [OK] CCM + surrogate test both included")

    # Scenario E: Predict with marginal data (should block)
    print("\n── Scenario E: Predict with marginal data (should block) ──")
    plan_e = quick_route(n_samples=30, is_regular=False, goal="predict")
    plan_e.print_plan()
    assert len(plan_e.blocks) >= 1
    print("  [OK] BLOCKED prediction on irregular data")

    # Scenario F: Serialization
    print("\n── Scenario F: Plan serialization ──")
    d = plan_a.to_dict()
    assert 'data_grade' in d
    assert 'steps' in d
    assert len(d['steps']) >= 3
    print(f"  [OK] Plan serialized: {len(d['steps'])} steps, "
          f"grade={d['data_grade']}, label={d['label']}")

    print("\n" + "=" * 64)
    print("  Router: ALL SCENARIOS PASSED")
    print("=" * 64)
